name: Continuous Integration/Continuous Deployment
on: [push]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      REGION: ${{ secrets.REGION }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Update Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Set environment and bring the model
        run: |
          pip install dvc-gs
          python utilities/setter.py
          dvc pull model/model.pkl.dvc -r model-tracker

      - name: Set up GCLOUD SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          version: 'latest'
          install_components: 'kubectl'

      - name: Build and Push
        run: |
          docker build . -t $REGISTRY_NAME:$GITHUB_SHA
          docker push $REGISTRY_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update $SERVICE_NAME --region=$REGION --image=$REGISTRY_NAME:$GITHUB_SHA